### ISSUE TITLE
 VLE activity not showing all students names

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#105]
![image](https://cloud.githubusercontent.com/assets/1846710/26784415/5d18c42a-49f5-11e7-9d22-4a41e0a162be.png)

VLE activity by student – some names were not showing e.g. Introduction to Business Law (first one is staff member) above. https://x.data.alpha.jisc.ac.uk/#/modules/BM4004%2FA22%2FUMS%2F2016%2F17, but I note there are no longer missing names (note I can verify that the test one at the bottom is our test account). I can't find another example either, though note some such as https://x.data.alpha.jisc.ac.uk/#/modules/PG6005%2FA13%2FPMS%2F2016%2F17 have no names against the 's number'.

I note that on large modules e.g. https://x.data.alpha.jisc.ac.uk/#/modules/BM4116%2FA11%2FUMS%2F2016%2F17, https://x.data.alpha.jisc.ac.uk/#/modules/SP4018%2FA12%2FUMS%2F2016%2F17, only every other name is shown, so you have to hover on the line to see which students are in between - could the display settings be altered so that every student is listed? 

Ticket: https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/54

**Comment by leebaylis** [comment]
Submitted by Gloucester

**Comment by michaelwebbjisc** [comment]
I think this is when the student isn't register on the module, but has looked at the module anyway.  I'll verify this.  Probably the best thing would be to exclude these by default.

The way it works is that it looks up all the module members first, and then matches them to student ids when it draws the graph.  This means it's only looking up the student names from a very small group. Doing it for everyone would be really slow.

**Comment by michaelwebbjisc** [comment]
These were students not in the UDD so are now excluded from the view

**Comment by robbristow-jisc** [comment]
Some weirdness going on here.
If I go to Glos, 2016, and go to All Modules, I get the list of modules. Click on one - say the first one - Introduction to Quantitative Methods, ID: AC4002/A12/UMS takes me to a screen that defaults to VLE by Student with only 4 students showing. 
However clicking ion the second Introduction to Quantitative Methods module defaults to VLE Activity by Week. If I select VLE activity - Student use distribution, I only seem to see three or four students. Is that correct? Or no students in the case of Business Law AC5004/A12/UMS
I See from the original raising of this ticket that the visualisation where the problem  showing up was called VLE Activity by Student - but there is no option called that in the visualisation drop down now.
Could do with some guidance on how to process here, as I am not sure that I am able to say that the bug is fixed at this point.

**Comment by michaelwebbjisc** [comment]
This is actually related to this one:

https://github.com/jiscdev/data-explorer/issues/242

ie the non-resolving names where people that weren't on that module. I'm going to close this particular one, and leave the development task in 242, as we need to decide how to handle these if we are only showing module members,
