### ISSUE TITLE
Enhanced Demo Mode

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#123]
This is an internal requirement for Jisc, so not formally part of the sprint cycle.  I've added it here though for completeness.

It has been developer as a 0.11.x feature branch, but will be pulled to 0.12 rather than 0.11 now.

**Comment by robbristow-jisc** [comment]
I don't know what this means!

**Comment by leebaylis** [comment]
Good shout!
Now when you log in and get a list of LRWs there should be a Demo entry in the list -- if you click that there should be enough data to be able to follow through the script at
https://jiscdev.atlassian.net/wiki/display/LA/Data+Explorer+%28DataX%29+-+Demo+Script
I think that will satisfy the test!

**Comment by robbristow-jisc** [comment]
I've found an issue here. I followed the script, as you said, Lee. I Click on Bobby Brooks, and see the modules, but the screen with the drilled into information says "Student Module Overview: Alice Scott" at the top. Is that a known Issue. 

Otherwise I think see the detail as described in the script. Would like to discus this further to ensure I am not missing something

**Comment by leebaylis** [comment]
@michaelwebbjisc is bobby brooks/Alice scott a known data issue?
