### ISSUE TITLE
API end point to describe verbs

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#124]
eg

describe?verb=http://id.tincanapi.com/verb/viewed

would return 'The user viewed something online, often in a VLE'.

**Comment by pdiveris** [comment]
I have added the API side and deployed on DEV and STAGING. However, I can't assign to Rob for testing as there is no UI around it (it can only be tested using Postman right now.)

**Comment by leebaylis** [comment]
yep, assign things like this to me for testing instead

**Comment by pdiveris** [comment]
Are you going to be 
testing on staging or dev?




     
   	leebaylis        3 
August 2017 at 13:29    
  yep, assign things like this
 to me for testing instead

—You
 are receiving this because you were assigned.Reply to this email 
directly, view
 it on GitHub, or mute
 the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jiscdev/data-explorer","title":"jiscdev/data-explorer","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer">"https://github.com/jiscdev/data-explorer"</a>}},"updates":{"snippets
":[{"icon":"PERSON","message":"@leebaylis in #124: yep, assign things like this to me for testing instead"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer/issues/124#issuecomment-319954946">"https://github.com/jiscdev/data-explorer/issues/124#issuecomment-319954946"</a>}}}
  
     
   	Michael Webb        19 
June 2017 at 09:28    
  eg
describe?verb=http://id.tincanapi.com/verb/viewed
would return 'The user viewed something online, often in a VLE'.

—You
 are receiving this because you are subscribed to this thread.Reply 
to this email directly, view it on 
GitHub, or mute
 the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jiscdev/data-explorer","title":"jiscdev/data-explorer","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer">"https://github.com/jiscdev/data-explorer"</a>}},"updates":{"snippets
":[{"icon":"DESCRIPTION","message":"API end point to describe verbs (#124)"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer/issues/124">"https://github.com/jiscdev/data-explorer/issues/124"</a>}}}
  


-- Petros
 Diveris

+44 (0) 7771 608 617
Manchester, UK

**Comment by leebaylis** [comment]
if there's a label for just dev then there; if both then staging

**Comment by pdiveris** [comment]
You should be able to run tests using Postman. Something weird happens with staging - when doing requests other than GET you get a HTTP 502 response back, even though the request was successful. Don't do the POST or DEL again, just try a get to see where you are at. I am workingon the UI so this should be obsoleted shortly.
