### ISSUE TITLE
 No way of knowing which tutor you are impersonating 

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#146]
from https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/287

Site Explorer on the menu, All Tutors, then pick a good tutor who has data e.g. the 26th tutor in the list from Glos live.

But: Once you have picked one of the buttons e.g. Tutor View, you have nothing to tell you who you are.

Suggest the header is altered to say e.g. Tutor Overview for Lee Baylis (or whoever)

Ditto for Module view.

![image](https://user-images.githubusercontent.com/1846710/28059878-803f79dc-661d-11e7-94bd-e537665f01f2.png)

**Comment by robbristow-jisc** [comment]
That seems to work as desired - I can now see the (correct) name of the tutor when clicking into Tutor detail

**Comment by leebaylis** [comment]
Good job, works when impersonating a tutor but doesn't work when I click my own tutees, e.g.

https://x-dev.data.alpha.jisc.ac.uk/#/tutor/me

Shall we add it in there as well?

**Comment by pdiveris** [comment]
Yes willlook to it




     
   	leebaylis        2 
August 2017 at 10:28    
  Good job, works when 
impersonating a tutor but doesn't work when I click my own tutees, e.g.
https://x-dev.data.alpha.jisc.ac.uk/#/tutor/me
Shall we add it in there as well?

—You
 are receiving this because you were assigned.Reply to this email 
directly, view
 it on GitHub, or mute
 the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jiscdev/data-explorer","title":"jiscdev/data-explorer","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer">"https://github.com/jiscdev/data-explorer"</a>}},"updates":{"snippets
":[{"icon":"PERSON","message":"@leebaylis in #146: Good job, works when impersonating a tutor but doesn't work when I click my own tutees, e.g.\r\n\r\nhttps://x-dev.data.alpha.jisc.ac.uk/#/tutor/me\r\n\r\nShall we add it in there as well?"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer/issues/146#issuecomment-319619668">"https://github.com/jiscdev/data-explorer/issues/146#issuecomment-319619668"</a>}}}
  
     
   	leebaylis        11 
July 2017 at 09:45    
  from https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/287
Site Explorer on the menu, All Tutors, then pick a good tutor who has
 data e.g. the 26th tutor in the list from Glos live.
But: Once you have picked one of the buttons e.g. Tutor View, you 
have nothing to tell you who you are.
Suggest the header is altered to say e.g. Tutor Overview for Lee 
Baylis (or whoever)
Ditto for Module view.


—You
 are receiving this because you are subscribed to this thread.Reply 
to this email directly, view it on 
GitHub, or mute
 the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jiscdev/data-explorer","title":"jiscdev/data-explorer","subtitle":"GitHub repository","main_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png"</a>,"avatar_image_url":<a class="moz-txt-link-rfc2396E" href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png"</a>,"action":{"name":"Open in GitHub","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer">"https://github.com/jiscdev/data-explorer"</a>}},"updates":{"snippets
":[{"icon":"DESCRIPTION","message":" No way of knowing which tutor you are impersonating  (#146)"}],"action":{"name":"View Issue","url":<a class="moz-txt-link-rfc2396E" href="https://github.com/jiscdev/data-explorer/issues/146">"https://github.com/jiscdev/data-explorer/issues/146"</a>}}}
  


-- Petros
 Diveris

+44 (0) 7771 608 617
Manchester, UK

**Comment by michaelwebbjisc** [comment]
Comments say tested and working.  I've tested to and looks fine, so closing.
