### ISSUE TITLE
Changing year does not refresh the current graph

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#175]
see
https://github.com/jiscdev/data-explorer/issues/51#issuecomment-320917869

I can change the academic year in the drop down however what is displayed does not seem not change - I have the same data on screen regardless of which year I am looking at. Is this supposed to change?

suggest that this is an entirely different issue (it's a a series of fixes in all components i.e. Students Overview, Tutors Overview etc.

**Comment by pdiveris** [comment]
This could somehow become an epic. In a sense the core of this issue has been dealt with, however we need to discuss what we want to happen in each specific component, and do it. 

Here's the notes from Slack pertaining to this branch of work:

As of last weekend I am now catching the year change event and, having assigned a method to it, I am running a refresh of the component upon change in its value. The promise is defined in a parent class, so with a bit of refactoring any component that needs to listen to external events and do something can simply derive from DataXComponent.

There are a couple of issues here:

1. At the moment, upon change I simply run `ngInit()` which does the trick. However, it overdoes it. There is code in `ngInit()` which doesn’t need to run again to simply perform a refresh. I suggest that we plan a move of the code absolutely neceesary to _redraw_ a viz to a separate method, which can/will be called from `ngInit()` as well as a new `refresh()` method.

2. The initialisation of module-overview.componet is a bit more complicated, as we have the date dropdowns. Same applies to visualisations which bring the “last 14 days,” so a decision needs to be made and a plan drawn as to what’s the expected behaviour when people change academic year.

The goods news here is that he have tackled ~~some~~ the core of it, bad news is that the two items above cannot be done before this release, perhaps not even in the next sprint, especially as MW is away.

The other bad news is that to achieve this I stopped my *Highcharts* work on Friday, work on which three issues in here rely, and which need doing for this next release. So I am now very thin on time, but I hope that I’ll just about manage

**Comment by leebaylis** [comment]
Noted to ask user group what they want as behaviour in next meeting. Parked until then.

**Comment by leebaylis** [comment]
now referenced by https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/353

**Comment by michaelwebbjisc** [comment]
Feature removed
